version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 13.4.1 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme 'Drop Rename All'

  build:
    macos:
      xcode: 13.4.1 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip 'build/Release/Drop Rename All.app'
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
  deploy:
    macos:
      xcode: 13.4.1 # indicate your selected version of Xcode
    stops:
      - run:
          name: artifact link (set CIRCLE_TOKEN_READONLY from API Permissions)
          command: curl -H "Circle-Token: $CIRCLE_TOKEN_READONLY" https://circleci.com/api/v1.1/project/github/b23prodtm/simplerenamescript/latest/artifacts

workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
